### ISSUE TITLE
[Crash] crash app when calling Pushdy.getPendingNotifications() in android.

### ISSUE THREAD

**Issue by kyunkakata** [Pushdy/react-native-pushdy#2]
Description:
I want to check pending notifications so that I call like this:

```
const pendNotids = await Pushdy.getPendingNotifications();
console.log("{checkMe}: handleInitialNotification -> pendNotids", pendNotids)
```
The app crashed immediately then throw error:
[image](https://imgur.com/a/iLEOd6w)

**Comment by luatnd** [comment]
Fixed, plz use the updated version 0.0.12 to see if the error was fixed
